{
    "n_steps": 1,
    "cum_reward": 0,
    "cum_raw_reward": 0,
    "err_msg": "Exception uncaught by agent or environment in task webarena.81.\nAuthenticationError:\nError code: 401 - {'error': {'message': 'Incorrect API key provided: sk-Yzyb1***************************************3f14. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}",
    "stack_trace": "Traceback (most recent call last):\n  File \"/Users/pujiayue/Documents/research/llm agent hallucination/BG_for_hallucination/browsergym/experiments/src/browsergym/experiments/loop.py\", line 440, in run\n    step_info.from_step(env, action, obs_preprocessor=agent.obs_preprocessor)\n  File \"/Users/pujiayue/Documents/research/llm agent hallucination/BG_for_hallucination/browsergym/experiments/src/browsergym/experiments/loop.py\", line 184, in from_step\n    self.obs, self.reward, self.terminated, self.truncated, env_info = env.step(action)\n                                                                       ^^^^^^^^^^^^^^^^\n  File \"/opt/anaconda3/envs/hallu/lib/python3.12/site-packages/gymnasium/wrappers/common.py\", line 125, in step\n    observation, reward, terminated, truncated, info = self.env.step(action)\n                                                       ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/anaconda3/envs/hallu/lib/python3.12/site-packages/gymnasium/wrappers/common.py\", line 393, in step\n    return super().step(action)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/anaconda3/envs/hallu/lib/python3.12/site-packages/gymnasium/core.py\", line 327, in step\n    return self.env.step(action)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/pujiayue/Documents/research/llm agent hallucination/BG_for_hallucination/browsergym/core/src/browsergym/core/env.py\", line 433, in step\n    reward, done, user_message, task_info = self._task_validate()\n                                            ^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/pujiayue/Documents/research/llm agent hallucination/BG_for_hallucination/browsergym/core/src/browsergym/core/env.py\", line 458, in _task_validate\n    reward, done, user_message, info = self.task.validate(self.page, self.chat.messages)\n                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/pujiayue/Documents/research/llm agent hallucination/BG_for_hallucination/browsergym/webarena/src/browsergym/webarena/task.py\", line 201, in validate\n    score = self.evaluator(\n            ^^^^^^^^^^^^^^^\n  File \"<@beartype(webarena.evaluation_harness.evaluators.EvaluatorComb.__call__) at 0x11ae69440>\", line 115, in __call__\n  File \"/opt/anaconda3/envs/hallu/lib/python3.12/site-packages/webarena/evaluation_harness/evaluators.py\", line 359, in __call__\n    cur_score = evaluator(trajectory, config_file, page, client)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/anaconda3/envs/hallu/lib/python3.12/site-packages/webarena/evaluation_harness/evaluators.py\", line 167, in __call__\n    score *= self.fuzzy_match(\n             ^^^^^^^^^^^^^^^^^\n  File \"<@beartype(webarena.evaluation_harness.evaluators.StringEvaluator.fuzzy_match) at 0x11ae68d60>\", line 69, in fuzzy_match\n  File \"/opt/anaconda3/envs/hallu/lib/python3.12/site-packages/webarena/evaluation_harness/evaluators.py\", line 116, in fuzzy_match\n    return llm_fuzzy_match(pred, ref, intent)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/anaconda3/envs/hallu/lib/python3.12/site-packages/webarena/evaluation_harness/helper_functions.py\", line 161, in llm_fuzzy_match\n    response = generate_from_openai_chat_completion(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/anaconda3/envs/hallu/lib/python3.12/site-packages/webarena/llms/providers/openai_utils.py\", line 75, in wrapper\n    raise e\n  File \"/opt/anaconda3/envs/hallu/lib/python3.12/site-packages/webarena/llms/providers/openai_utils.py\", line 55, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/anaconda3/envs/hallu/lib/python3.12/site-packages/webarena/llms/providers/openai_utils.py\", line 258, in generate_from_openai_chat_completion\n    response = client.chat.completions.create(# type: ignore\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/anaconda3/envs/hallu/lib/python3.12/site-packages/openai/_utils/_utils.py\", line 279, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/anaconda3/envs/hallu/lib/python3.12/site-packages/openai/resources/chat/completions/completions.py\", line 914, in create\n    return self._post(\n           ^^^^^^^^^^^\n  File \"/opt/anaconda3/envs/hallu/lib/python3.12/site-packages/openai/_base_client.py\", line 1242, in post\n    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/anaconda3/envs/hallu/lib/python3.12/site-packages/openai/_base_client.py\", line 919, in request\n    return self._request(\n           ^^^^^^^^^^^^^^\n  File \"/opt/anaconda3/envs/hallu/lib/python3.12/site-packages/openai/_base_client.py\", line 1023, in _request\n    raise self._make_status_error_from_response(err.response) from None\nopenai.AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: sk-Yzyb1***************************************3f14. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}\n",
    "stats.cum_steps": 2,
    "stats.cum_n_token_goal": 27,
    "stats.max_n_token_goal": 27,
    "stats.cum_n_token_url": 24,
    "stats.max_n_token_url": 24,
    "stats.cum_n_token_focused_element_bid": 1,
    "stats.max_n_token_focused_element_bid": 1,
    "stats.cum_n_token_last_action": 0,
    "stats.max_n_token_last_action": 0,
    "stats.cum_n_token_last_action_error": 0,
    "stats.max_n_token_last_action_error": 0,
    "stats.cum_n_token_dom_txt": 13647,
    "stats.max_n_token_dom_txt": 13647,
    "stats.cum_n_token_axtree_txt": 1911,
    "stats.max_n_token_axtree_txt": 1911,
    "stats.cum_n_token_pruned_html": 11945,
    "stats.max_n_token_pruned_html": 11945,
    "stats.cum_n_retry_llm": 1,
    "stats.max_n_retry_llm": 1,
    "stats.cum_n_retry": 0.0,
    "stats.max_n_retry": 0.0,
    "stats.cum_busted_retry": 0,
    "stats.max_busted_retry": 0,
    "stats.cum_input_tokens": 3210,
    "stats.max_input_tokens": 3210,
    "stats.cum_output_tokens": 565,
    "stats.max_output_tokens": 565,
    "stats.cum_cost": 0.0,
    "stats.max_cost": 0.0,
    "stats.cum_n_token_agent_messages": 3242,
    "stats.max_n_token_agent_messages": 3242,
    "stats.cum_step_elapsed": 12.444561958312988,
    "stats.max_step_elapsed": 12.444561958312988,
    "stats.cum_agent_elapsed": 9.289026021957397,
    "stats.max_agent_elapsed": 9.289026021957397,
    "terminated": null,
    "truncated": null
}